services:
  web:
    image: sajeel007/devops-challenge:latest # Use YOUR image!
    ports:
      - "8080:80"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 # Checks for updates every 30 seconds (aggressive for testing!)
